language: c
dist: trusty
sudo: required
notifications:
  email: false
git:
  submodules: true
  depth: 3
matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - zip=linux_32
    install:
    - sudo apt-get install -y gcc-multilib
    - sudo apt-get install -y libc6-dev-i386
    script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_FLAGS=-m32
    - cmake --build . --config Release
  - os: linux
    compiler: gcc
    env:
    - zip=linux_64
    script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_FLAGS=-m64
    - cmake --build . --config Release
  - os: osx
    compiler: gcc
    env:
    - zip=mac_universal
    script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --config Release
after_success:
- cd ../
- mv bin spam
- cp LICENSE spam/license.txt
- cp README.md spam/readme.txt
- mv spam/ylm/README.md spam/ylm/readme.txt
- mv spam/xel/README.md spam/xel/readme.txt
- mv spam/zpt/README.md spam/zpt/readme.txt
- zip -r spam_$zip.zip spam
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AZdWnhrfpdGX1uI56Y8t1Drms30Y88T8Ni5UAUfB5vyvQPE33uFPMYlRGII5+s7OIqk+9MUvDUzSsUM0XjxuJ3aHYfFBS15c2Tcrl7uURWfGvmTolXKaz+SNCxnxrepq3eF7zKA38qO8BDwjW3uVfa8XODX6LQt4oAp2zAYgFQ4tcskzsp8vOKaIeicqAgXtNPoPtz3FJbVbA8UZpa8HUOhT7+gf0qO3emdQ+FaWU086eIvFyQI+IRY0dJnG4pL8dtDe2795GBccuyzwbEh0wy/lifeHRCfT3qLoELunG92fA7i6wTO2ViiiSd8O+rxnqqN1CIAnG/VuTy/0FrAWzp+TS/4c9A17YwDao9Q28dhCnRKHduinjOhxe5DqffMuC6yomGB77wXqsaO80mknri6eIN9hBdz9UI9gLznNoHi1/HNKiIWaVBwoUdqDquQgtoAMHi4TGk6MvW5ddNTEOrp3Xf4nLUYOHAg+MqMEBqzaRsQlrlEbDzJIEmtwx2H/n3FfQIxYKhJjMvHhHX1nvHaLU8Y+SbXTfH6YtghXfn8PUyh5V3WRDw6k7itB5a/HYNHa4jvOE6EDIcJJ6SKCk6kL73nP9kPWWAK22fdZwsuS5QcHthflGOWQDf3b3sr26x1I6FNKxIxct0bMP0zTrGS88VT3oBU8uURTBfuI4bE=
  file: spam_$zip.zip
  on:
    rtags: true
    repo: pierreguillot/spam
