
environment:
   matrix:
      - CONFIGURATION: Release
        PLATFORM: Win32
        ZIP: spam_win_32
      - CONFIGURATION: Release
        PLATFORM: x64
        ZIP: spam_win_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - git clone -q --branch=master https://github.com/pierreguillot/pdwinlib.git
    - cd pdwinlib
    - cd ..\

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
    - cmake --build .

after_build:
    - cd ..\
    - del /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\*.pdb
    - del /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\*.ilk
    - rename %APPVEYOR_BUILD_FOLDER%\spam\ylm\README.md readme.txt
    - rename %APPVEYOR_BUILD_FOLDER%\spam\soxel\README.md readme.txt
    - rename %APPVEYOR_BUILD_FOLDER%\spam\zpt\README.md readme.txt
    - copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\spam\readme.txt
    - copy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\spam\license.txt
    - 7z a %ZIP%.zip %APPVEYOR_BUILD_FOLDER%\spam\

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: hFOC0oRou0A7cFLF/0b5hyXE/lXyb1oa2dg6LdSyT5Je70m0DQAJ5cKa4cUbvfWe
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
