
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
        ZIP: spam_win_32
      - CONFIGURATION: Debug
        PLATFORM: x64
        ZIP: spam_win_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - git clone -q --branch=master https://github.com/pierreguillot/pdwinlib.git
    - cd pdwinlib
    - dir /s /b /o:gn
    - cd ..\

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
    - cmake --build .

after_build:
    - cd ..\
    - rename %APPVEYOR_BUILD_FOLDER%\bin\spam_in.dll spam.in.dll
    - rename %APPVEYOR_BUILD_FOLDER%\bin\spam_out.dll spam.out.dll
    - rename %APPVEYOR_BUILD_FOLDER%\bin\spam_in_tilde.dll spam.in~.dll
    - rename %APPVEYOR_BUILD_FOLDER%\bin\spam_out_tilde.dll spam.out~.dll
    - rename %APPVEYOR_BUILD_FOLDER%\bin\spam_tilde.dll spam~.dll
    - rename %APPVEYOR_BUILD_FOLDER%\bin\spam_connect.dll spam.connect.dll
    - rename %APPVEYOR_BUILD_FOLDER%\bin\spam.dll spam.dll
    - del /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\*.pdb
    - del /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\*.ilk
    - rename %APPVEYOR_BUILD_FOLDER%\bin spam
    - xcopy /E %APPVEYOR_BUILD_FOLDER%\ylm\* %APPVEYOR_BUILD_FOLDER%\spam\ylm\*
    - rename %APPVEYOR_BUILD_FOLDER%\spam\ylm\README.md readme.txt
    - xcopy /E %APPVEYOR_BUILD_FOLDER%\mat\* %APPVEYOR_BUILD_FOLDER%\spam\mat\*
    - rename %APPVEYOR_BUILD_FOLDER%\spam\mat\README.md readme.txt
    - copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\spam\readme.txt
    - copy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\spam\license.txt
    - 7z a %ZIP%.zip %APPVEYOR_BUILD_FOLDER%\spam\

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: hFOC0oRou0A7cFLF/0b5hyXE/lXyb1oa2dg6LdSyT5Je70m0DQAJ5cKa4cUbvfWe
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
