
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
      - CONFIGURATION: Debug
        PLATFORM: x64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - git clone -q --branch=master https://github.com/pierreguillot/pdwinlib.git
    - cd pdwinlib
    - dir /s /b /o:gn
    - cd ..\

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
    - cmake --build .

after_build:
    - cd ..\
    - DIR
    - DEL /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\*.pdb
    - DEL /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\*.ilk
    - RENAME %APPVEYOR_BUILD_FOLDER%\bin spam
    - 7z a spam_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\spam\
    - DIR

artifacts:
  - path: spam_%PLATFORM%.zip

notifications:

  - provider: Email
    on_build_status_changed: false
